#!/bin/sh

# /*
#	This file is part of ghtml.
#
#    ghtml is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ghtml is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ghtml.  If not, see <http://www.gnu.org/licenses/>.
#
# */

# This file demonstrates a typical @installhook
# it does exactly the same thing as if you would have called apps/install ghtml-jseval
# and this file did not exist.

# This system exists so we can copy multiple files, rather than just a single file if 
# need be. Your file does not have to be a shell file, it can be any script or program.

echo ""

[[ -w "$installDir" ]] || {

	echo -e You don\'t have sufficient privileges to'\n'"install" \
	\'$byApplication\' to \'$installDir\''\n';

	exit 1;
} >&2;

shared_dir=/usr/share/mrkdnv;

mkdir -p $shared_dir{,/themes};

status=`install -vt "$installDir" "$byApplication" 2>&1 || \
echo -n "$this: $group: installation failed to copy: " >&2;`;

status=`install -vt "$shared_dir" "apps/mrkdnv/Markdown/Markdown.pl" 2>&1 || \
echo -n "$this: $group: installation failed to copy: " >&2;`;

status=`install -vt "$shared_dir/themes" apps/mrkdnv/themes/* 2>&1 || \
echo -n "$this: $group: installation failed to copy: " >&2;`;

echo "$status";

echo "";

