#!/bin/bash

lib=/usr/share/mrkdnv/Markdown.pl;

[[ -e $lib ]] || {
	errno=$?;
	echo $0: error: unable to locate markdown library: resolution: re-install mrkdnv;
	exit $errno;
} >&2;

(( $debug )) && {
	debug=-D;
}

# Environment config +(default)
title=${1:-${title:-Markdown Viewer}};	
d=${2:-${dimensions:-720x480}};
file=${3:-${file:--}};

perl "$lib" --html4tags "${file}" \
|	 ghtml ${debug:--}d --width ${d%*x} --height ${d#*x} --title "${title:-${file#*/}}" \
	-o "${onload:-}" \
& disown $!;

