#!/bin/sh

# /*
#	This file is part of ghtml.
#
#    ghtml is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ghtml is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ghtml.  If not, see <http://www.gnu.org/licenses/>.
#
# */

group="$1"; test $# -gt 0 && shift 1;

test "$1" = '-e' && { exec=true; test $# -gt 0 && shift 1; }

title="$1";

test $# -gt 0 && { shift 1; }
 
this="$0" localPath="${this%/*}" installGroup="$localPath/$group/@group";
installDefault="/usr/bin" installDir="${INSTALLDIR:-$installDefault}";

test "$group" = --help || test "$group" = -h || test "$group" = '-?' || \
test -z "$group" && {

echo '\n'USAGE: $this group [-e] [title]';\n';

echo "DESCRIPTION: Install the application by its group name and";
echo "title to environment variable INSTALLDIR or $installDefault"'\n';

echo "group: The name of the path in $localPath";
echo "title: The name of the file in: $localPath/group"'\n';

echo "If option -e is supplied, execute the title, with remaining arguments,";
echo "instead of copying it. If title is not supplied with -e list group executables" \
'\n';

echo "If title is not supplied, execute $localPath/group/@group";
echo "if that program is not present, try to install";
echo "$localPath/group/group and if that fails show a listing";
echo "of all valid resources belonging to group"'\n';

echo "if title is -- all following arguments are passed to ";
echo "$localPath/group/@group"'\n';

test -w "$installDir" ||
echo You must have sufficient privileges to perform this operation.'\n';

exit;

}

byInstallGroup="$localPath/$group/@group";
byInstallGroupTitle="$localPath/$group/$title";
byApplication="$localPath/$group/$group";

test "$exec" = "true" && {

	test -x "$byInstallGroupTitle" && test -n "$title"  && {
		exec "$byInstallGroupTitle" "$@";
	} || {
		echo '\n'"Listing of executable targets for $group:"'\n'
		(
			for file in `cd "$localPath/$group"; printf "%s\n" *`; do
				test -x "$localPath/$group/$file" && {
					haveTargets=true;
					echo "$file";
				}
			done
			test "$haveTargets" = "true" || echo NO TARGETS AVAILABLE FOR GROUP;
		);  echo ""; 
	};  exit;

}

test -z "$title" || test "$title" = '--' && {
	test -e "$byInstallGroup" && { (
		export this group title localPath installGroup installDefault installDir \
		byApplication; exec "$byInstallGroup" "$@";
	);   exit;
	}
	resource="$byApplication";
} || {
	resource="$byInstallGroupTitle";
}

echo "";
test ! -e "$resource" && {
	(   cd "$localPath/$group";
		echo "Listing of resources in $group:"'\n';
		list=`echo -n *`
		test -z "$list" && echo NO RESOURCES AVAILABLE FOR GROUP'\n' || echo \
		"$list"'\n'
	);  exit 1;
}

test -w $installDir || {
	echo "You don't have sufficient privileges to perform this operation."'\n';
	exit 1;
} >&2;

status=`cp -vt "$installDir" "$resource" 2>&- || \
echo -n "$this: $group: installation failed to copy: " >&2;`;

echo "$status";

echo "";

